services:
  test-db:
    image: postgres:15
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - test_pgdata:/var/lib/postgresql/data

  test-redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - test_redisdata:/data

  test-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql+asyncpg://test_user:test_password@test-db:5432/test_db
      - REDIS_URL=redis://test-redis:6379/0
      - JWT_SECRET_KEY=test_secret_key
      - ENVIRONMENT=testing
    depends_on:
      - test-db
      - test-redis
    volumes:
      - .:/code
    command: pytest --cov=app

volumes:
  test_pgdata:
  test_redisdata: