services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - backend
      
  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend


  redis:  
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - backend
    command: redis-server --appendonly yes --requirepass 12345

volumes:
  pgdata:
    driver: local
  redisdata:  
    driver: local


networks:
  backend:
    driver: bridge