"""deletedAt Resume Table

Revision ID: 8ce0c1023e83
Revises: 9043d04bad77
Create Date: 2025-09-17 14:38:28.634282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce0c1023e83'
down_revision: Union[str, Sequence[str], None] = '9043d04bad77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###
    op.alter_column('resume', 'is_deleted', server_default=None)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'is_deleted')
    # ### end Alembic commands ###
