"""update table user_resume

Revision ID: 9043d04bad77
Revises: b14a8ef97308
Create Date: 2025-09-17 12:11:40.889639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9043d04bad77'
down_revision: Union[str, Sequence[str], None] = 'b14a8ef97308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_default_resume'), 'resume', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_user_default_resume'), 'resume', ['user_id', 'is_default'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
