"""update resume table

Revision ID: 9dea6d03d66a
Revises: 4077dce5c08e
Create Date: 2025-09-17 11:15:47.112401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dea6d03d66a'
down_revision: Union[str, Sequence[str], None] = '4077dce5c08e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumeview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'application', 'user', ['reviewed_by'], ['id'])
    op.create_foreign_key(None, 'application', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'auditlog', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'company', 'user', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'companymember', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'invitation', 'user', ['invited_by'], ['id'])
    op.create_foreign_key(None, 'job', 'user', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'job', 'user', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'message', 'user', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'message', 'user', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'message', 'user', ['recipient_id'], ['id'])
    op.create_foreign_key(None, 'notification', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'performancemetric', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'performancemetric', type_='foreignkey')
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_constraint(None, 'invitation', type_='foreignkey')
    op.drop_constraint(None, 'companymember', type_='foreignkey')
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_constraint(None, 'auditlog', type_='foreignkey')
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_table('resumeview')
    # ### end Alembic commands ###
