"""update table user_resume

Revision ID: b14a8ef97308
Revises: 9dea6d03d66a
Create Date: 2025-09-17 12:02:13.571147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b14a8ef97308'
down_revision: Union[str, Sequence[str], None] = '9dea6d03d66a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumeview', sa.Column('resume_id', sa.Integer(), nullable=False))
    op.add_column('resumeview', sa.Column('viewer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'resumeview', 'resume', ['resume_id'], ['id'])
    op.create_foreign_key(None, 'resumeview', 'user', ['viewer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumeview', type_='foreignkey')
    op.drop_constraint(None, 'resumeview', type_='foreignkey')
    op.drop_column('resumeview', 'viewer_id')
    op.drop_column('resumeview', 'resume_id')
    # ### end Alembic commands ###
