"""Add all tables

Revision ID: e1368a8d85f3
Revises: 
Create Date: 2025-08-30 12:17:39.009795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1368a8d85f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_category_active', 'categories', ['is_active'], unique=False)
    op.create_index('idx_category_name', 'categories', ['name'], unique=False)
    op.create_index('idx_category_parent', 'categories', ['parent_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('candidate', 'employer', name='userrole'), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_user_active', 'user', ['is_active'], unique=False)
    op.create_index('idx_user_email', 'user', ['email'], unique=False)
    op.create_index('idx_user_role', 'user', ['role'], unique=False)
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('employment_type', sa.String(length=50), nullable=False),
    sa.Column('skills_required', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_active_expires', 'job', ['is_active', 'expires_at'], unique=False)
    op.create_index('idx_job_category', 'job', ['category_id'], unique=False)
    op.create_index('idx_job_employment_type', 'job', ['employment_type'], unique=False)
    op.create_index('idx_job_location', 'job', ['location'], unique=False)
    op.create_index('idx_job_salary', 'job', ['salary'], unique=False)
    op.create_index('idx_job_user', 'job', ['user_id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=100), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_chat', 'message', ['chat_id'], unique=False)
    op.create_index('idx_message_created', 'message', ['created_at'], unique=False)
    op.create_index('idx_message_recipient', 'message', ['recipient_id'], unique=False)
    op.create_index('idx_message_sender', 'message', ['sender_id'], unique=False)
    op.create_index('idx_message_unread', 'message', ['recipient_id', 'is_read'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('message', 'application', 'job_update', 'system', name='notificationtype'), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_created', 'notification', ['created_at'], unique=False)
    op.create_index('idx_notification_type', 'notification', ['type'], unique=False)
    op.create_index('idx_notification_unread', 'notification', ['user_id', 'is_read'], unique=False)
    op.create_index('idx_notification_user', 'notification', ['user_id'], unique=False)
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('experience', sa.String(), nullable=False),
    sa.Column('skills', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resume_default', 'resume', ['is_default'], unique=False)
    op.create_index('idx_resume_public', 'resume', ['is_public'], unique=False)
    op.create_index('idx_resume_user', 'resume', ['user_id'], unique=False)
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'REVIEWED', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_application_job', 'application', ['job_id'], unique=False)
    op.create_index('idx_application_status', 'application', ['status'], unique=False)
    op.create_index('idx_application_user', 'application', ['user_id'], unique=False)
    op.create_index('idx_application_user_job', 'application', ['user_id', 'job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_application_user_job', table_name='application')
    op.drop_index('idx_application_user', table_name='application')
    op.drop_index('idx_application_status', table_name='application')
    op.drop_index('idx_application_job', table_name='application')
    op.drop_table('application')
    op.drop_index('idx_resume_user', table_name='resume')
    op.drop_index('idx_resume_public', table_name='resume')
    op.drop_index('idx_resume_default', table_name='resume')
    op.drop_table('resume')
    op.drop_index('idx_notification_user', table_name='notification')
    op.drop_index('idx_notification_unread', table_name='notification')
    op.drop_index('idx_notification_type', table_name='notification')
    op.drop_index('idx_notification_created', table_name='notification')
    op.drop_table('notification')
    op.drop_index('idx_message_unread', table_name='message')
    op.drop_index('idx_message_sender', table_name='message')
    op.drop_index('idx_message_recipient', table_name='message')
    op.drop_index('idx_message_created', table_name='message')
    op.drop_index('idx_message_chat', table_name='message')
    op.drop_table('message')
    op.drop_index('idx_job_user', table_name='job')
    op.drop_index('idx_job_salary', table_name='job')
    op.drop_index('idx_job_location', table_name='job')
    op.drop_index('idx_job_employment_type', table_name='job')
    op.drop_index('idx_job_category', table_name='job')
    op.drop_index('idx_job_active_expires', table_name='job')
    op.drop_table('job')
    op.drop_index('idx_user_role', table_name='user')
    op.drop_index('idx_user_email', table_name='user')
    op.drop_index('idx_user_active', table_name='user')
    op.drop_table('user')
    op.drop_index('idx_category_parent', table_name='categories')
    op.drop_index('idx_category_name', table_name='categories')
    op.drop_index('idx_category_active', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
